sudo: required
install: travis_wait mvn install
services:
  - docker

before_install:
  - docker build -t daimonos/docker-react -f Dockerfile.dev .

script:
  - docker run daimonos/docker-react npm run test -- --coverage